name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y webp librsvg2-bin

    - name: Optimization
      run: |
        chmod +x optimize.sh
        ./optimize.sh -i src/tracks -h 600 -q 100 -o out
        ./optimize.sh -i src/artists -h 300 -q 100 -o out
        ./optimize.sh -i src/playlists -h 300 -q 100 -o out

    - name: Deploy
      run: |
        sudo chown -R $(whoami):$(whoami) .
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        cp -r out/* /tmp
        cd /tmp
        git init
        git branch -M gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
        git push -f origin gh-pages
